<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="FVFDN4SYP3XY" failures="1" tests="4" name="Surefire test" time="5.247" errors="0" timestamp="28 Mar 2024 11:19:46 GMT">
  <testcase classname="MealPlanTest" name="AddItemMealPlanTest" time="2.414"/>
  <testcase classname="MealPlanTest" name="DeleteItemToMealPlanTest" time="0.768">
    <failure type="groovy.lang.GroovyRuntimeException" message="could not access constructor: private java.lang.AssertionError(java.lang.String) with arguments: [1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
] reason: java.lang.IllegalAccessException: class org.codehaus.groovy.reflection.CachedConstructor cannot access a member of class java.lang.AssertionError (in module java.base) with modifiers &amp;quot;private&amp;quot;">
      <![CDATA[groovy.lang.GroovyRuntimeException: could not access constructor: private java.lang.AssertionError(java.lang.String) with arguments: [1 expectation failed.Expected status code <200> but was <404>.at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:494)at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:656)at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:125)at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:133)at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:119)at MealPlanTest.DeleteItemToMealPlanTest(MealPlanTest.java:90)at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)at java.base/java.lang.Thread.run(Thread.java:1583)... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- DeleteItemToMealPlanTest -->
  <testcase classname="MealPlanTest" name="MealPlanGenerateTest" time="0.951"/>
  <testcase classname="RecipeTest" name="MealPlanSearchRecipesTest" time="1.041"/>
  <testcase classname="BaseTest" name="@AfterSuite TearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite TearDownSuite -->
  <testcase classname="BaseTest" name="@BeforeSuite SetUpSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite SetUpSuite -->
</testsuite> <!-- Surefire test -->
